# Generated by Django 6.0.1 on 2026-01-27 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='user_upload_index',
            field=models.IntegerField(default=1, editable=False),
        ),
    ]
